package jp.ne.ruru.park.ando.snmpviewer.tree;


/* Generated By:JavaCC: Do not edit this line. AsnParserTreeConstants.java Version 6.1_2 */
public interface AsnParserTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTMODULEDEFINITION = 1;
  public int JJTTAGDEFAULT = 2;
  public int JJTMODULEIDENTIFIER = 3;
  public int JJTASSIGNEDIDENTIFIER = 4;
  public int JJTMODULEBODY = 5;
  public int JJTEXPORTS = 6;
  public int JJTSYMBOLSEXPORTED = 7;
  public int JJTEXPORTSYMBOLLIST = 8;
  public int JJTIMPORTS = 9;
  public int JJTSYMBOLSIMPORTED = 10;
  public int JJTSYMBOLSFROMMODULELIST = 11;
  public int JJTSYMBOLSFROMMODULE = 12;
  public int JJTSYMBOLLIST = 13;
  public int JJTSYMBOL = 14;
  public int JJTASSIGNMENTLIST = 15;
  public int JJTASSIGNMENT = 16;
  public int JJTMACRODEFINITION = 17;
  public int JJTMACROBODY = 18;
  public int JJTMACROREFERENCE = 19;
  public int JJTTYPEASSIGNMENT = 20;
  public int JJTTYPE = 21;
  public int JJTGLOBALTYPE = 22;
  public int JJTDEFINEDMACRONAME = 23;
  public int JJTDEFINEDTYPE = 24;
  public int JJTBUILTINTYPE = 25;
  public int JJTOCTETSTRINGTYPE = 26;
  public int JJTOBJECTIDENTIFERTYPE = 27;
  public int JJTREALTYPE = 28;
  public int JJTBOOLEANTYPE = 29;
  public int JJTNULLTYPE = 30;
  public int JJTEXTERNALTYPE = 31;
  public int JJTENUMERATEDTYPE = 32;
  public int JJTINTEGERTYPE = 33;
  public int JJTBITSTRINGTYPE = 34;
  public int JJTSETORSEQUENCEOFTYPE = 35;
  public int JJTCHOICETYPE = 36;
  public int JJTSETORSEQUENCETYPE = 37;
  public int JJTSELECTIONTYPE = 38;
  public int JJTTAGGEDTYPE = 39;
  public int JJTTAG = 40;
  public int JJTANYTYPE = 41;
  public int JJTNAMEDNUMBERLIST = 42;
  public int JJTNAMEDNUMBER = 43;
  public int JJTSIGNEDNUMBER = 44;
  public int JJTELEMENTTYPELIST = 45;
  public int JJTELEMENTTYPE = 46;
  public int JJTCOMPONENTSTYPE = 47;
  public int JJTNAMEDTYPE = 48;
  public int JJTCLASSNUMBER = 49;
  public int JJTCLASS = 50;
  public int JJTSUBTYPESPEC = 51;
  public int JJTSUBTYPEVALUESETLIST = 52;
  public int JJTSUBTYPEVALUESET = 53;
  public int JJTCONTAINEDSUBTYPE = 54;
  public int JJTSINGLEVALUE = 55;
  public int JJTVALUERANGE = 56;
  public int JJTSIZECONSTRAINT = 57;
  public int JJTPERMITTEDALPHABET = 58;
  public int JJTINNERTYPECONSTRAINTS = 59;
  public int JJTSINGLETYPECONSTRAINT = 60;
  public int JJTMULTIPLETYPECONSTRAINTS = 61;
  public int JJTTYPECONSTRAINTS = 62;
  public int JJTNAMEDCONSTRAINT = 63;
  public int JJTCONSTRAINT = 64;
  public int JJTVALUECONSTRAINT = 65;
  public int JJTPRESENCECONSTRAINT = 66;
  public int JJTVALUEASSIGNMENT = 67;
  public int JJTVALUE = 68;
  public int JJTDEFINEDVALUE = 69;
  public int JJTBUILTINVALUE = 70;
  public int JJTCOMPOUNDVALUE = 71;
  public int JJTSKIP_TO_MATCHING_BRACE = 72;
  public int JJTBOOLEANVALUE = 73;
  public int JJTSPECIALREALVALUE = 74;
  public int JJTNULLVALUE = 75;
  public int JJTNAMEDVALUE = 76;
  public int JJTOBJECTIDENTIFIERVALUE = 77;
  public int JJTOBJIDCOMPONENTLIST = 78;
  public int JJTOBJIDCOMPONENT = 79;
  public int JJTNUMBERFORM = 80;
  public int JJTNAMEANDNUMBERFORM = 81;
  public int JJTBINARYSTRING = 82;
  public int JJTHEXSTRING = 83;
  public int JJTCHARSTRING = 84;
  public int JJTNUMBER = 85;
  public int JJTIDENTIFIER = 86;
  public int JJTMODULEREFERENCE = 87;
  public int JJTTYPEREFERENCE = 88;
  public int JJTTEXTUALCONVENTIONMACROTYPE = 89;
  public int JJTMODULEIDENTITYMACROTYPE = 90;
  public int JJTNOTIFICATIONTYPEMACROTYPE = 91;
  public int JJTNOTIFICATIONGROUPMACROTYPE = 92;
  public int JJTMODULECOMPLIANCEMACROTYPE = 93;
  public int JJTOBJECGROUPMACROTYPE = 94;
  public int JJTOBJECIDENTITYMACROTYPE = 95;
  public int JJTTRAPTYPEMACROTYPE = 96;
  public int JJTAGENTCAPABILITIESMACROTYPE = 97;
  public int JJTOBJECTTYPEMACROTYPE = 98;
  public int JJTSNMPDISPLAYHINTPART = 99;
  public int JJTSNMPOBJECTSPART = 100;
  public int JJTSNMPNITIFICATIONSPART = 101;
  public int JJTSNMPSTATUS = 102;
  public int JJTSNMPACCESS = 103;
  public int JJTSNMPDESCRPART = 104;
  public int JJTSNMPREFERENCEPART = 105;
  public int JJTSNMPINDEXPART = 106;
  public int JJTSNMPEXTENDSPART = 107;
  public int JJTSNMPUNIQUENESSPART = 108;
  public int JJTTYPEORVALUELIST = 109;
  public int JJTTYPEORVALUE = 110;
  public int JJTSNMPDEFVALPART = 111;
  public int JJTSNMPDEFVALSUBPART = 112;
  public int JJTSNMPDEFVALSUBSUBPART = 113;
  public int JJTSNMPDEFVALSUBSUBSUBPART = 114;
  public int JJTSNMPAUGMENTSPART = 115;
  public int JJTSNMPINSTALLERRORSPART = 116;
  public int JJTSNMPSUBJECTCATEGORIESPART = 117;
  public int JJTSNMPLASTUPDATEDPART = 118;
  public int JJTSNMPORGANIZATIONPART = 119;
  public int JJTSNMPCONTACTINFOPART = 120;
  public int JJTSNMPREVISIONPART = 121;
  public int JJTSNMPREFERENCESPART = 122;
  public int JJTSNMPSYNTAXPART = 123;
  public int JJTSNMPWRITESYNTAXPART = 124;
  public int JJTSNMPENTERPRISEPART = 125;
  public int JJTSNMPVARIABLESPART = 126;
  public int JJTSNMPUNITSPART = 127;
  public int JJTSNMPTAGPART = 128;
  public int JJTSNMPMANDATORYGROUPSPART = 129;
  public int JJTSNMPGROUPPART = 130;
  public int JJTSNMPOBJECTPART = 131;
  public int JJTSNMPPRODUCTRELEASEPART = 132;
  public int JJTSNMPSUPPORTSPART = 133;
  public int JJTSNMPINCLUDESPART = 134;
  public int JJTSNMPVALIATIONPART = 135;


  public String[] jjtNodeName = {
    "Input",
    "ModuleDefinition",
    "TagDefault",
    "ModuleIdentifier",
    "AssignedIdentifier",
    "ModuleBody",
    "Exports",
    "SymbolsExported",
    "ExportSymbolList",
    "Imports",
    "SymbolsImported",
    "SymbolsFromModuleList",
    "SymbolsFromModule",
    "SymbolList",
    "Symbol",
    "AssignmentList",
    "Assignment",
    "MacroDefinition",
    "MacroBody",
    "MacroReference",
    "TypeAssignment",
    "Type",
    "GlobalType",
    "DefinedMacroName",
    "DefinedType",
    "BuiltinType",
    "OctetStringType",
    "ObjectIdentiferType",
    "RealType",
    "BooleanType",
    "NullType",
    "ExternalType",
    "EnumeratedType",
    "IntegerType",
    "BitStringType",
    "SetOrSequenceOfType",
    "ChoiceType",
    "SetOrSequenceType",
    "SelectionType",
    "TaggedType",
    "Tag",
    "AnyType",
    "NamedNumberList",
    "NamedNumber",
    "SignedNumber",
    "ElementTypeList",
    "ElementType",
    "ComponentsType",
    "NamedType",
    "ClassNumber",
    "Class",
    "SubtypeSpec",
    "SubtypeValueSetList",
    "SubtypeValueSet",
    "ContainedSubtype",
    "SingleValue",
    "ValueRange",
    "SizeConstraint",
    "PermittedAlphabet",
    "InnerTypeConstraints",
    "SingleTypeConstraint",
    "MultipleTypeConstraints",
    "TypeConstraints",
    "NamedConstraint",
    "Constraint",
    "ValueConstraint",
    "PresenceConstraint",
    "ValueAssignment",
    "Value",
    "DefinedValue",
    "BuiltinValue",
    "CompoundValue",
    "skip_to_matching_brace",
    "BooleanValue",
    "SpecialRealValue",
    "NullValue",
    "NamedValue",
    "ObjectIdentifierValue",
    "ObjIdComponentList",
    "ObjIdComponent",
    "NumberForm",
    "NameAndNumberForm",
    "BinaryString",
    "HexString",
    "CharString",
    "number",
    "identifier",
    "modulereference",
    "typereference",
    "TextualConventionMacroType",
    "ModuleIdentityMacroType",
    "NotificationTypeMacroType",
    "NotificationGroupMacroType",
    "ModuleComplianceMacroType",
    "ObjecGroupMacroType",
    "ObjecIdentityMacroType",
    "TrapTypeMacroType",
    "AgentCapabilitiesMacroType",
    "ObjectTypeMacroType",
    "SnmpDisplayHintPart",
    "SnmpObjectsPart",
    "SnmpNitificationsPart",
    "SnmpStatus",
    "SnmpAccess",
    "SnmpDescrPart",
    "SnmpReferencePart",
    "SnmpIndexPart",
    "SnmpExtendsPart",
    "SnmpUniquenessPart",
    "TypeOrValueList",
    "TypeOrValue",
    "SnmpDefValPart",
    "SnmpDefValSubPart",
    "SnmpDefValSubSubPart",
    "SnmpDefValSubSubSubPart",
    "SnmpAugmentsPart",
    "SnmpInstallErrorsPart",
    "SnmpSubjectCategoriesPart",
    "SnmpLastUpdatedPart",
    "SnmpOrganizationPart",
    "SnmpContactInfoPart",
    "SnmpRevisionPart",
    "SnmpReferencesPart",
    "SnmpSyntaxPart",
    "SnmpWriteSyntaxPart",
    "SnmpEnterprisePart",
    "SnmpVariablesPart",
    "SnmpUnitsPart",
    "SnmpTagPart",
    "SnmpMandatoryGroupsPart",
    "SnmpGroupPart",
    "SnmpObjectPart",
    "SnmpProductReleasePart",
    "SnmpSupportsPart",
    "SnmpIncludesPart",
    "SnmpValiationPart",
  };
}
/* JavaCC - OriginalChecksum=521378a929537989d5f48c5df2459757 (do not edit this line) */
