package jp.ne.ruru.park.ando.snmpviewer.tree;


/* Generated By:JJTree&JavaCC: Do not edit this line. AsnParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AsnParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OBJECT_IDENTIFIER_TKN = 8;
  /** RegularExpression Id. */
  int BSTRING_TKN = 9;
  /** RegularExpression Id. */
  int HSTRING_TKN = 10;
  /** RegularExpression Id. */
  int CSTRING_TKN = 11;
  /** RegularExpression Id. */
  int PLUS_NUMBER_TKN = 12;
  /** RegularExpression Id. */
  int MINUS_NUMBER_TKN = 13;
  /** RegularExpression Id. */
  int DOT_TKN = 14;
  /** RegularExpression Id. */
  int COMMA_TKN = 15;
  /** RegularExpression Id. */
  int LEFTBRACE_TKN = 16;
  /** RegularExpression Id. */
  int RIGHTBRACE_TKN = 17;
  /** RegularExpression Id. */
  int LEFTPAREN_TKN = 18;
  /** RegularExpression Id. */
  int RIGHTPAREN_TKN = 19;
  /** RegularExpression Id. */
  int LEFTBRACKET_TKN = 20;
  /** RegularExpression Id. */
  int RIGHTBRACKET_TKN = 21;
  /** RegularExpression Id. */
  int LESSTHAN_TKN = 22;
  /** RegularExpression Id. */
  int MINUS_TKN = 23;
  /** RegularExpression Id. */
  int GETS_TKN = 24;
  /** RegularExpression Id. */
  int BAR_TKN = 25;
  /** RegularExpression Id. */
  int SEMI_COLON_TKN = 26;
  /** RegularExpression Id. */
  int SELECTOR_TKN = 27;
  /** RegularExpression Id. */
  int TC_TKN = 28;
  /** RegularExpression Id. */
  int MI_TKN = 29;
  /** RegularExpression Id. */
  int NT_TKN = 30;
  /** RegularExpression Id. */
  int NG_TKN = 31;
  /** RegularExpression Id. */
  int MC_TKN = 32;
  /** RegularExpression Id. */
  int OG_TKN = 33;
  /** RegularExpression Id. */
  int OI_TKN = 34;
  /** RegularExpression Id. */
  int TT_TKN = 35;
  /** RegularExpression Id. */
  int AC_TKN = 36;
  /** RegularExpression Id. */
  int OBJECTTYPE_TKN = 37;
  /** RegularExpression Id. */
  int ABSENT_TKN = 38;
  /** RegularExpression Id. */
  int ACCESS_TKN = 39;
  /** RegularExpression Id. */
  int ANY_TKN = 40;
  /** RegularExpression Id. */
  int APPLICATION_TKN = 41;
  /** RegularExpression Id. */
  int AUGMENTS_TKN = 42;
  /** RegularExpression Id. */
  int BEGIN_TKN = 43;
  /** RegularExpression Id. */
  int BIT_TKN = 44;
  /** RegularExpression Id. */
  int BOOLEAN_TKN = 45;
  /** RegularExpression Id. */
  int BY_TKN = 46;
  /** RegularExpression Id. */
  int CHOICE_TKN = 47;
  /** RegularExpression Id. */
  int COMPONENT_TKN = 48;
  /** RegularExpression Id. */
  int COMPONENTS_TKN = 49;
  /** RegularExpression Id. */
  int CONTACT_INFO_TKN = 50;
  /** RegularExpression Id. */
  int DEFAULT_TKN = 51;
  /** RegularExpression Id. */
  int DEFINED_TKN = 52;
  /** RegularExpression Id. */
  int DEFINITIONS_TKN = 53;
  /** RegularExpression Id. */
  int DEFVAL_TKN = 54;
  /** RegularExpression Id. */
  int DESCRIPTION_TKN = 55;
  /** RegularExpression Id. */
  int DHINT = 56;
  /** RegularExpression Id. */
  int END_TKN = 57;
  /** RegularExpression Id. */
  int ENTERPRISE_TKN = 58;
  /** RegularExpression Id. */
  int ENUMERATED_TKN = 59;
  /** RegularExpression Id. */
  int EXPLICIT_TKN = 60;
  /** RegularExpression Id. */
  int EXPORTS_TKN = 61;
  /** RegularExpression Id. */
  int EXTENDS_TKN = 62;
  /** RegularExpression Id. */
  int EXTERNAL_TKN = 63;
  /** RegularExpression Id. */
  int FALSE_TKN = 64;
  /** RegularExpression Id. */
  int FROM_TKN = 65;
  /** RegularExpression Id. */
  int GROUP_TKN = 66;
  /** RegularExpression Id. */
  int IMPLICIT_TKN = 67;
  /** RegularExpression Id. */
  int IMPLIED_TKN = 68;
  /** RegularExpression Id. */
  int IMPORTS_TKN = 69;
  /** RegularExpression Id. */
  int INCLUDES_TKN = 70;
  /** RegularExpression Id. */
  int INDEX_TKN = 71;
  /** RegularExpression Id. */
  int INSTALL_ERRORS_TKN = 72;
  /** RegularExpression Id. */
  int INTEGER_TKN = 73;
  /** RegularExpression Id. */
  int LAST_UPDATED_TKN = 74;
  /** RegularExpression Id. */
  int MACRO_TKN = 75;
  /** RegularExpression Id. */
  int MANDATORY_GROUPS_TKN = 76;
  /** RegularExpression Id. */
  int MAX_TKN = 77;
  /** RegularExpression Id. */
  int MIN_TKN = 78;
  /** RegularExpression Id. */
  int MINUS_INFINITY_TKN = 79;
  /** RegularExpression Id. */
  int MODULE_TKN = 80;
  /** RegularExpression Id. */
  int NOTIFICATIONS_TKN = 81;
  /** RegularExpression Id. */
  int NULL_TKN = 82;
  /** RegularExpression Id. */
  int OBJECT_TKN = 83;
  /** RegularExpression Id. */
  int OBJECTS_TKN = 84;
  /** RegularExpression Id. */
  int OCTET_TKN = 85;
  /** RegularExpression Id. */
  int OF_TKN = 86;
  /** RegularExpression Id. */
  int OPTIONAL_TKN = 87;
  /** RegularExpression Id. */
  int ORGANIZATION_TKN = 88;
  /** RegularExpression Id. */
  int PLUS_INFINITY_TKN = 89;
  /** RegularExpression Id. */
  int PRESENT_TKN = 90;
  /** RegularExpression Id. */
  int PRIVATE_TKN = 91;
  /** RegularExpression Id. */
  int PRODUCT_RELEASE_TKN = 92;
  /** RegularExpression Id. */
  int REAL_TKN = 93;
  /** RegularExpression Id. */
  int REFERENCE_TKN = 94;
  /** RegularExpression Id. */
  int REFERENCES_TKN = 95;
  /** RegularExpression Id. */
  int REVISION_TKN = 96;
  /** RegularExpression Id. */
  int SEQUENCE_TKN = 97;
  /** RegularExpression Id. */
  int SET_TKN = 98;
  /** RegularExpression Id. */
  int SIZE_TKN = 99;
  /** RegularExpression Id. */
  int STATUS_TKN = 100;
  /** RegularExpression Id. */
  int STRING_TKN = 101;
  /** RegularExpression Id. */
  int SUBJECT_CATEGORIES_TKN = 102;
  /** RegularExpression Id. */
  int SUPPORTS_TKN = 103;
  /** RegularExpression Id. */
  int SYNTAX_TKN = 104;
  /** RegularExpression Id. */
  int TAG_TKN = 105;
  /** RegularExpression Id. */
  int TAGS_TKN = 106;
  /** RegularExpression Id. */
  int TRUE_TKN = 107;
  /** RegularExpression Id. */
  int UNIQUENESS_TKN = 108;
  /** RegularExpression Id. */
  int UNITS_TKN = 109;
  /** RegularExpression Id. */
  int UNIVERSAL_TKN = 110;
  /** RegularExpression Id. */
  int VARIABLES_TKN = 111;
  /** RegularExpression Id. */
  int VARIATION_TKN = 112;
  /** RegularExpression Id. */
  int WITH_TKN = 113;
  /** RegularExpression Id. */
  int WRITE_SYNTAX_TKN = 114;
  /** RegularExpression Id. */
  int LCASEFIRST_IDENT_TKN = 115;
  /** RegularExpression Id. */
  int UCASEFIRST_IDENT_TKN = 116;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinASNComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"--\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<OBJECT_IDENTIFIER_TKN>",
    "<BSTRING_TKN>",
    "<HSTRING_TKN>",
    "<CSTRING_TKN>",
    "<PLUS_NUMBER_TKN>",
    "<MINUS_NUMBER_TKN>",
    "\".\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\"-\"",
    "\"::=\"",
    "\"|\"",
    "\";\"",
    "\":\"",
    "\"TEXTUAL-CONVENTION\"",
    "\"MODULE-IDENTITY\"",
    "\"NOTIFICATION-TYPE\"",
    "\"NOTIFICATION-GROUP\"",
    "\"MODULE-COMPLIANCE\"",
    "\"OBJECT-GROUP\"",
    "\"OBJECT-IDENTITY\"",
    "\"TRAP-TYPE\"",
    "\"AGENT-CAPABILITIES\"",
    "\"OBJECT-TYPE\"",
    "\"ABSENT\"",
    "<ACCESS_TKN>",
    "\"ANY\"",
    "\"APPLICATION\"",
    "\"AUGMENTS\"",
    "\"BEGIN\"",
    "\"BIT\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"CHOICE\"",
    "\"COMPONENT\"",
    "\"COMPONENTS\"",
    "\"CONTACT-INFO\"",
    "\"DEFAULT\"",
    "\"DEFINED\"",
    "<DEFINITIONS_TKN>",
    "\"DEFVAL\"",
    "\"DESCRIPTION\"",
    "\"DISPLAY-HINT\"",
    "\"END\"",
    "\"ENTERPRISE\"",
    "\"ENUMERATED\"",
    "\"EXPLICIT\"",
    "\"EXPORTS\"",
    "\"EXTENDS\"",
    "\"EXTERNAL\"",
    "\"FALSE\"",
    "\"FROM\"",
    "\"GROUP\"",
    "\"IMPLICIT\"",
    "\"IMPLIED\"",
    "\"IMPORTS\"",
    "\"INCLUDES\"",
    "<INDEX_TKN>",
    "\"INSTALL-ERRORS\"",
    "\"INTEGER\"",
    "\"LAST-UPDATED\"",
    "\"MACRO\"",
    "\"MANDATORY-GROUPS\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"MINUS-INFINITY\"",
    "\"MODULE\"",
    "\"NOTIFICATIONS\"",
    "\"NULL\"",
    "\"OBJECT\"",
    "\"OBJECTS\"",
    "\"OCTET\"",
    "\"OF\"",
    "\"OPTIONAL\"",
    "\"ORGANIZATION\"",
    "\"PLUS-INFINITY\"",
    "\"PRESENT\"",
    "\"PRIVATE\"",
    "\"PRODUCT-RELEASE\"",
    "\"REAL\"",
    "<REFERENCE_TKN>",
    "<REFERENCES_TKN>",
    "\"REVISION\"",
    "\"SEQUENCE\"",
    "\"SET\"",
    "\"SIZE\"",
    "\"STATUS\"",
    "\"STRING\"",
    "\"SUBJECT-CATEGORIES\"",
    "\"SUPPORTS\"",
    "\"SYNTAX\"",
    "<TAG_TKN>",
    "\"TAGS\"",
    "\"TRUE\"",
    "\"UNIQUENESS\"",
    "\"UNITS\"",
    "\"UNIVERSAL\"",
    "\"VARIABLES\"",
    "\"VARIATION\"",
    "\"WITH\"",
    "\"WRITE-SYNTAX\"",
    "<LCASEFIRST_IDENT_TKN>",
    "<UCASEFIRST_IDENT_TKN>",
  };

}
